NETWORK_PASSPHRASE = "Test SDF Network ; September 2022"
SIGNING_KEY = "GCXYQCZWWAJPZR7CJ5KN3QA2GQ5ROXUNZTIS6QHXEZCBIZZD5ZVNE6HD"
HORIZON_URL = "https://horizon-testnet.stellar.org"
ACCOUNTS = [ "GANJJURFTOQHX36OZRAGWZBGH5TXNAVCRKQSCMXH6VFU657MJ7NR7FE5", "GCQUOPVUV42T32GL22HBM3Z2TCOWUTHSECTBVFYKVXIRNN76DA33Z3PL" ]


TRANSFER_SERVER = "https://stellartomlorg.herokuapp.com/sep6"
TRANSFER_SERVER_SEP0024 = "https://stellartomlorg.herokuapp.com/sep24"
WEB_AUTH_ENDPOINT = "https://stellartomlorg.herokuapp.com/auth"
KYC_SERVER = "https://stellartomlorg.herokuapp.com/kyc"
DIRECT_PAYMENT_SERVER = "https://stellartomlorg.herokuapp.com/sep31"
QUOTE_SERVER = "https://stellartomlorg.herokuapp.com/sep38"

[DOCUMENTATION]
ORG_NAME = " "
ORG_URL = " "
ORG_LOGO = " "
ORG_PHYSICAL_ADDRESS = " "
ORG_OFFICIAL_EMAIL = " "
ORG_GITHUB = " "
ORG_TWITTER = " "
ORG_KEYBASE = " "
ORG_DESCRIPTION = " "


[[PRINCIPALS]]
name = " "
email = " "
github = " "
twitter = " "
Keybase = " "


[[CURRENCIES]]
code = "LHTSD"
image = " "
issuer = "GANJJURFTOQHX36OZRAGWZBGH5TXNAVCRKQSCMXH6VFU657MJ7NR7FE5"
is_asset_anchored = false
anchor_asset_type = "Digital"
desc = "Leeway Hertz Technologies Stellar Dollar (LHTSD) is an asset issued on testnet and is used as an anchored asset for this reference server for demonstration and testing purposes."
